"""Compatibility schema for Reporter Pro DOCX templates."""

from __future__ import annotations

from typing import Any

COMPATIBILITY_VERSION = "1.0"
KNOWN_REPORT_TYPES = {
    "full",
    "server_only",
    "client_only",
    "summary",
    "technical",
    "incident_response",
}

_FULL_TEMPLATE_TABLES = {
    "full": {"inventory_server", "inventory_client", "summary_server", "summary_client", "detail"},
    "server_only": {"inventory_server", "summary_server", "detail"},
    "client_only": {"inventory_client", "summary_client", "detail"},
    "summary": {"summary_server", "summary_client"},
    "technical": {"inventory_server", "inventory_client", "detail", "ioc"},
    "incident_response": {"ioc"},
}


def evaluate_template_compatibility(
    analysis: dict[str, Any], report_type: str = "full"
) -> dict[str, Any]:
    """Classify a template without rejecting safe cover-only templates.

    Cover templates are completed by the report engine, so missing prototype tables are
    warnings. A template declaring a full document contract must contain the structural
    prototype tables required by its report type.
    """
    normalized_type = report_type if report_type in KNOWN_REPORT_TYPES else "full"
    errors: list[dict[str, str]] = []
    warnings: list[dict[str, str]] = []
    guidance: list[str] = []

    if analysis.get("error"):
        errors.append(
            {"code": "ANALYSIS_FAILED", "item": "document", "message": str(analysis["error"])}
        )

    mode = analysis.get("template_mode", "none")
    found_tokens = set(analysis.get("tokens_found", []))
    unknown_tokens = analysis.get("unknown_tokens", [])
    found_tables = set(analysis.get("prototype_tables", []))

    if mode == "none":
        errors.append(
            {
                "code": "NO_USABLE_STRUCTURE",
                "item": "document",
                "message": "Template does not contain a usable cover or report structure.",
            }
        )
        guidance.append("Add a cover page or at least one Heading style before uploading again.")

    if "{{TITLE}}" not in found_tokens:
        warnings.append(
            {
                "code": "MISSING_TITLE_TOKEN",
                "item": "{{TITLE}}",
                "message": "The title token is missing; the engine will use the document title/cover fallback.",
            }
        )
        guidance.append("Add {{TITLE}} where the generated report title should appear.")

    for token in unknown_tokens:
        warnings.append(
            {
                "code": "UNKNOWN_TOKEN",
                "item": token,
                "message": f"Token {token} is not supported by compatibility version {COMPATIBILITY_VERSION}.",
            }
        )
    if unknown_tokens:
        guidance.append("Replace unknown tokens with a supported token or plain text.")

    required_tables = _FULL_TEMPLATE_TABLES[normalized_type]
    missing_tables = sorted(required_tables - found_tables)
    if mode == "full":
        for table in missing_tables:
            errors.append(
                {
                    "code": "MISSING_REQUIRED_TABLE",
                    "item": table,
                    "message": f"Full {normalized_type} template is missing prototype table: {table}.",
                }
            )
        if missing_tables:
            guidance.append(
                "Add the missing prototype tables with the exact header names shown in the template guide."
            )
    elif missing_tables:
        warnings.append(
            {
                "code": "ENGINE_GENERATED_SECTIONS",
                "item": ", ".join(missing_tables),
                "message": "Required report sections will be generated by the engine after the cover.",
            }
        )

    status = "incompatible" if errors else "compatible_with_warnings" if warnings else "compatible"
    return {
        "status": status,
        "version": COMPATIBILITY_VERSION,
        "reportType": normalized_type,
        "errors": errors,
        "warnings": warnings,
        "guidance": list(dict.fromkeys(guidance)),
        "requirements": {
            "requiredTokens": ["{{TITLE}}"],
            "requiredTables": sorted(required_tables),
            "mode": mode,
        },
    }


def compare_template_analysis(before: dict[str, Any], after: dict[str, Any]) -> dict[str, Any]:
    """Return a readable structural diff between two analyzed DOCX versions."""
    before_tokens, after_tokens = (
        set(before.get("tokens_found", [])),
        set(after.get("tokens_found", [])),
    )
    before_tables, after_tables = (
        set(before.get("prototype_tables", [])),
        set(after.get("prototype_tables", [])),
    )
    before_headings, after_headings = (
        set(before.get("heading_list", [])),
        set(after.get("heading_list", [])),
    )
    return {
        "templateMode": {
            "before": before.get("template_mode"),
            "after": after.get("template_mode"),
        },
        "tableCount": {
            "before": before.get("table_count", 0),
            "after": after.get("table_count", 0),
        },
        "headingCount": {
            "before": before.get("heading_count", 0),
            "after": after.get("heading_count", 0),
        },
        "tokens": {
            "added": sorted(after_tokens - before_tokens),
            "removed": sorted(before_tokens - after_tokens),
        },
        "prototypeTables": {
            "added": sorted(after_tables - before_tables),
            "removed": sorted(before_tables - after_tables),
        },
        "headings": {
            "added": sorted(after_headings - before_headings),
            "removed": sorted(before_headings - after_headings),
        },
        "compatibility": {
            "before": before.get("compatibility", {}).get("status", "unknown"),
            "after": after.get("compatibility", {}).get("status", "unknown"),
        },
    }
